[project]
name = "langchain-tutorial"
version = "0.1.0"
description = "This is a tutorial for LangChain, a framework for building applications with LLMs."
readme = "README.md"
authors = [
    { name = "gladsonits", email = "gladson.bits@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ddgs>=9.16.0",
    "detoxify>=0.5.2",
    "duckduckgo-search>=8.1.1",
    "email-validator>=2.3.0",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.2",
    "langchain-ollama>=1.1.0",
    "load-dotenv>=0.1.0",
    "ollama>=0.6.2",
    "openai>=3.8.0",
    "pandas>=3.0.6",
    "presidio>=2.2.364",
    "pydantic>=2.13.5",
    "torch>=2.14.0",
    "transformers>=5.17.0",
    "wikipedia>=1.4.0",
]

[project.scripts]
langchain-tutorial = "langchain_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
